# Generated by Django 4.2.17 on 2024-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0003_remove_rota_day_rota_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rota',
            name='date',
            field=models.DateField(),
        ),
    ]
