# Generated by Django 4.2.17 on 2024-12-17 15:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rota', '0004_request_admin_comment_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='shift_type',
            field=models.CharField(choices=[('Long Day', 'Long Day'), ('Early', 'Early'), ('Late', 'Late'), ('Night', 'Night'), ('Custom', 'Custom')], default='Long Day', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together={('user', 'date')},
        ),
    ]
