# Generated by Django 4.2.17 on 2024-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0005_alter_rota_shift_type_alter_rota_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
    ]
