# Generated by Django 4.2.17 on 2024-12-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0009_staffprofile_job_title_alter_staffprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='shift_type',
            field=models.CharField(choices=[('Long Day', 'Long Day'), ('Early', 'Early'), ('Late', 'Late'), ('Night', 'Night'), ('Custom', 'Custom')], default='Long Day', max_length=50),
        ),
    ]
