# Generated by Django 4.2.17 on 2024-12-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0010_alter_rota_shift_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rota',
            name='sickness_or_absence_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rota',
            name='shift_type',
            field=models.CharField(choices=[('Long Day', 'Long Day'), ('Early', 'Early'), ('Late', 'Late'), ('Night', 'Night'), ('Custom', 'Custom'), ('Sickness/Absence', 'Sickness/Absence')], default='Long Day', max_length=50),
        ),
    ]
