# Generated by Django 4.2.17 on 2024-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0013_alter_staffprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
