# Generated by Django 4.2.17 on 2024-12-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0015_alter_staffprofile_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rota',
            unique_together=set(),
        ),
    ]
