# Generated by Django 4.2.17 on 2024-12-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0016_alter_rota_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rota',
            name='shift_type',
            field=models.CharField(choices=[('Long Day', 'Long Day'), ('Early', 'Early'), ('Late', 'Late'), ('Night', 'Night'), ('Custom', 'Custom'), ('Requested Off', 'Requested Off'), ('Sickness/Absence', 'Sickness/Absence')], default='Long Day', max_length=50),
        ),
    ]
